apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"strapi-app-deployment","namespace":"atittan-ruangrit-dev"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":3000}],"selector":{"app":"strapi"},"type":"LoadBalancer"}}
  creationTimestamp: "2023-06-03T05:01:12Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: strapi-app-deployment
  namespace: atittan-ruangrit-dev
  resourceVersion: "187555791"
  uid: fdb6d124-902f-471d-a844-955b360811e1
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.30.73.151
  clusterIPs:
  - 172.30.73.151
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31065
    port: 80
    protocol: TCP
    targetPort: 1337
  selector:
    app: strapi
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
