apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: strapi-app-deployment
spec:
 selector:
   # Selector for Pods
   app: strapi
 ports:
   # Port Map
 - port: 80
   targetPort: 1337
   protocol: TCP
 type: LoadBalancer